export const DATA_CITY_INPUT_REQUEST = 'reducer/DATA_CITY_INPUT_REQUEST';
export const DATA_CITY_INPUT_SUCCESS = 'reducer/DATA_CITY_INPUT_SUCCESS';
export const DATA_CITY_INPUT_FAILED = 'reducer/DATA_CITY_INPUT_FAILED';