export const INFOMARTION_IMG_REQUEST = 'reducer/INFOMARTION_IMG_REQUEST';
export const INFOMARTION_IMG_SUCCESS = 'reducer/INFOMARTION_IMG_SUCCESS';
export const INFOMARTION_IMG_FAILED = 'reducer/INFOMARTION_IMG_FAILED';