export const HISTORYBOOOK_REQUEST = 'reducer/HISTORYBOOOK_REQUEST';
export const HISTORYBOOOK_SUCCESS = 'reducer/HISTORYBOOOK_SUCCESS';
export const HISTORYBOOOK_FAILED = 'reducer/HISTORYBOOOK_FAILED';