export const REGISTER_AIRBNB_REQUEST = 'reducer/REGISTER_AIRBNB_REQUEST';
export const REGISTER_AIRBNB_SUCCESS = 'reducer/REGISTER_AIRBNB_SUCCESS';
export const REGISTER_AIRBNB_FAILED = 'reducer/REGISTER_AIRBNB_FAILED';